---
# The myq cover platform lets you control MyQ-Enabled garage 
# doors through Home Assistant. Device names in Home Assistant 
# are generated based on the names defined in your MyQ Device 
# mobile app.

# https://www.home-assistant.io/integrations/myq/
cover:
 - platform: myq
   username: !secret myq_username
   password: !secret myq_password
 - platform: mqtt
   name: "Garage Door - Volvo"
   command_topic: "cmnd/tasmota_garage1/POWER"
   state_topic: "stat/tasmota_garage1/STATUS"
   availability_topic: "tele/tasmota_garage1/LWT"
   qos: 1
   payload_available: "Online"
   payload_not_available: "Offline"
   payload_open: "ON"
   payload_close: "ON"
   payload_stop: "ON"
   state_open: "open"
   state_closed: "closed"
   device_class: garage
 - platform: mqtt
   name: "Garage Door - VW"
   command_topic: "cmnd/tasmota_garage2/POWER"
   state_topic: "stat/tasmota_garage2/STATUS"
   availability_topic: "tele/tasmota_garage2/LWT"
   qos: 1
   payload_available: "Online"
   payload_not_available: "Offline"
   payload_open: "ON"
   payload_close: "ON"
   payload_stop: "ON"
   state_open: "open"
   state_closed: "closed"
   device_class: garage
  
# This is tracks the current state of the garage door. Current state is pushed
# periodically by tasmota
# 22:44:36 MQT: tele/tasmota_garage1/SENSOR = {"Time":"2020-10-14T22:44:36","Switch1":"OFF"}
binary_sensor:
  - platform: mqtt
    name: "Garage_Volvo_Sensor"
    state_topic: "tele/tasmota_garage1/SENSOR"
    payload_on: "ON"
    availability:
      - topic: "tele/tasmota_garage1/LWT"
        payload_available: "Online"
        payload_not_available: "Offline"
    qos: 0
    device_class: opening
    value_template: '{{ value_json.Switch1 }}'
  - platform: mqtt
    name: "Garage_VW_Sensor"
    state_topic: "tele/tasmota_garage2/SENSOR"
    payload_on: "ON"
    availability:
      - topic: "tele/tasmota_garage2/LWT"
        payload_available: "Online"
        payload_not_available: "Offline"
    qos: 0
    device_class: opening
    value_template: '{{ value_json.Switch1 }}'


# TimeZone 99
# TimeDST 0,2,3,1,2,-240
# TimeSTD 0,1,11,1,2,-300
# IPAddress1 <Static IP>
# switchmode1 2
# poweronstate 0
# setoption0 0
# pulsetime1 10
# Rule1 on switch1#state=0 do publish2 stat/%topic%/STATUS closed endon on switch1#state=1 do publish2 stat/%topic%/STATUS open endon
# Rule1 1
# setoption19 1 (to enable autodiscovery in homeassistant)