title: Home Control Panel
# resources: !include_dir_list lovelace/resources
resources:
  - url: /hacsfiles/weather-card/weather-card.js
    type: module
  - url: /hacsfiles/simple-thermostat/simple-thermostat.js
    type: module
views:
  - !include lovelace/views/downstairs.yaml
  - !include lovelace/views/upstairs.yaml
  - !include lovelace/views/cameras.yaml
  - !include lovelace/views/office.yaml
  - !include lovelace/views/battery.yaml
  # - !include lovelace/views/home_old.yaml
