title: Home Control Panel
# resources: !include_dir_list lovelace/resources
resources:
  - url: /hacsfiles/weather-card/weather-card.js
    type: module
  - url: /hacsfiles/simple-thermostat/simple-thermostat.js
    type: module
  - url: /hacsfiles/frigate-hass-card/frigate-hass-card.js
    type: module
  - url: /hacsfiles/lovelace-auto-entities/auto-entities.js
    type: module
  - url: /hacsfiles/lovelace-card-tools/card-tools.js
    type: module
  - url: /hacsfiles/lovelace-fold-entity-row/fold-entity-row.js
    type: module 
  - url: /hacsfiles/numberbox-card/numberbox-card.js
    type: module
views:
  - !include lovelace/views/downstairs.yaml
  - !include lovelace/views/upstairs.yaml
  - !include lovelace/views/cameras.yaml
  - !include lovelace/views/office.yaml
  - !include lovelace/views/front_door_lock.yaml
  - !include lovelace/views/garage_door_lock.yaml
  # - !include lovelace/views/home_old.yaml
