- alias: Turn on hallway lights when there is movement
  trigger:
    platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_a9fd1901_ias_zone
    to: 'on'
  action:
    service: light.turn_on
    data:
      entity_id: group.upstairs_hallway_lights
      brightness_pct: 80
      kelvin: 2700

- alias: Turn off hallway lights 2 minutes after last movement
  trigger:
    platform: state
    entity_id: binary_sensor.lumi_lumi_sensor_motion_a9fd1901_ias_zone
    to: 'off'
    for:
      minutes: 2
  action:
    service: light.turn_off
    entity_id: group.upstairs_hallway_lights