- alias: Turn on porch lights at sunset
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
    service: switch.turn_on
    entity_id: switch.jasco_products_12722_on_off_relay_switch_switch

- alias: Turn off porch lights at sunrise
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:30:00'
  action:
    service: switch.turn_off
    entity_id: switch.jasco_products_12722_on_off_relay_switch_switch
